import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const STORAGE_KEY = 'med_mate_language';

function readStoredLanguage() {
    try {
        if (typeof window === 'undefined') return 'en';
        const v = localStorage.getItem(STORAGE_KEY);
        return v === 'ur' || v === 'en' ? v : 'en';
    } catch {
        return 'en';
    }
}

export const LanguageProvider = ({ children }) => {
    const [language, setLanguageState] = useState(readStoredLanguage);

    useEffect(() => {
        document.documentElement.lang = language === 'ur' ? 'ur' : 'en';
    }, [language]);

    const setLanguage = (lang) => {
        if (lang !== 'en' && lang !== 'ur') return;
        setLanguageState(lang);
        try {
            localStorage.setItem(STORAGE_KEY, lang);
        } catch {
            /* ignore */
        }
    };

    const toggleLanguage = () => {
        setLanguage(language === 'en' ? 'ur' : 'en');
    };

    const translations = {
        en: {
            appName: 'Med-Mate',
            dashboard: 'Dashboard',
            myMeds: 'My Medicines',
            history: 'History',
            suggestions: 'Suggestions',
            profile: 'Profile',
            addMedicine: 'Add Medicine',
            nextDose: 'Next Dose',
            missed: 'Missed',
            taken: 'Taken',
            logout: 'Log Out',
            welcome: 'Welcome back',
            upcoming: 'Upcoming',
            completedMissed: 'Completed & Missed',
            noUpcoming: 'No upcoming medicines for today!',
            takeAction: 'Take',
            adminPanel: 'Admin Panel',
            adminSubtitle: 'System overview and patient assignments',
            loadingStats: 'Loading statistics…',
            systemOverview: 'System overview',
            patients: 'Patients',
            caretakers: 'Caretakers',
            unassignedPatients: 'Unassigned patients',
            totalMedicines: 'Total medicines',
            admins: 'Admins',
            verifiedUsers: 'Verified users',
            totalUsers: 'Total users',
            caretakersPatientsTitle: 'Caretakers & patient load',
            name: 'Name',
            email: 'Email',
            password: 'Password',
            assignedPatients: 'Assigned patients',
            noCaretakers: 'No caretakers registered yet.',
            unassignedSection: 'Unassigned patients',
            allPatientsAssigned: 'Every patient has a caretaker.',
            selectCaretaker: 'Select caretaker',
            assign: 'Assign',
            assigning: 'Assigning…',
            rolePatient: 'Patient',
            roleCaretaker: 'Caretaker',
            roleAdmin: 'Administrator',
            patientsMedicinesTitle: 'Patients & medicines',
            patientsMedicinesSubtitle: 'Which patient is taking which medicines',
            caretakerLabel: 'Caretaker',
            unassignedCaretaker: 'Unassigned',
            medName: 'Medicine',
            medDosage: 'Dosage',
            medTime: 'Time',
            medStatus: 'Status',
            medType: 'Type',
            noMedicinesListed: 'No medicines added yet.',
            noPatientsYet: 'No patients registered.',
            editName: 'Edit name',
            changePassword: 'Change password',
            firstNameLabel: 'First name',
            lastNameLabel: 'Last name',
            saveChanges: 'Save',
            cancel: 'Cancel',
            currentPasswordLabel: 'Current password',
            newPasswordLabel: 'New password',
            confirmPasswordLabel: 'Confirm new password',
            updatePasswordBtn: 'Update password',
            passwordsDoNotMatch: 'New passwords do not match',
            nameUpdateSuccess: 'Your name was updated',
            passwordUpdateSuccess: 'Your password was updated',
            saving: 'Saving…',
            updatingPassword: 'Updating…',
            languageUpdated: 'Language updated!',
            successTitle: 'All set',
            gotIt: 'Got it',
            medicineForPatient: 'Medicine for patient',
            selectPatientForMedicine: 'Please select which patient this medicine is for',
            noPatientsAddFirst: 'No patients yet — add a patient first',
            selectPatientPlaceholder: 'Select patient',
            addNewPatientTitle: 'Add new patient',
            addNewPatientSubtitle: 'Use the same details as at sign-up. The account is verified automatically.',
            dateOfBirthLabel: 'Date of birth',
            genderLabel: 'Gender',
            phoneLabel: 'Contact number',
            patientPasswordHint: 'The patient can use this password to log in to their account.',
            addPatientBtn: 'Add patient',
            addPatientNameError: 'First and last name must be at least 3 characters',
            passwordMin8: 'Password must be at least 8 characters',
            selectGender: 'Select gender',
            invalidPhone: 'Please enter a valid phone number',
            callPatient: 'Call patient',
            selectPatientToCall: 'Select a patient above to call',
            selectPatientToCallShort: 'Select a patient to call',
            caretakerDashboard: 'Caretaker dashboard',
            addPatientNav: 'Add Patient',
            switchToUrdu: 'Switch to Urdu',
            switchToEnglish: 'English',
            voiceCommandTitle: 'Voice Command',
            voiceListening: 'Listening…',
            voiceCommandBtn: 'Voice Command',
            voiceHeardPrefix: 'Heard:',
            voiceInvalidCommand: 'Invalid command',
            loginWelcomeBack: 'Welcome Back',
            loginSubtitle: 'Sign in to your account',
            enterEmailPlaceholder: 'Enter your email',
            forgotPasswordLink: 'Forgot Password?',
            signInBtn: 'Sign In',
            noAccount: "Don't have an account?",
            createAccountLink: 'Create Account',
            loginFailed: 'Login failed',
            loginErrorGeneric: 'An error occurred during login',
            signupTitle: 'Create Account',
            signupSubtitle: 'Join Med-Mate today',
            signupFirstNameError: 'First name must be at least 3 characters',
            signupLastNameError: 'Last name must be at least 3 characters',
            signupPasswordError: 'Password must be at least 8 characters',
            signupGenderError: 'Please select a gender',
            signupPhoneError: 'Please enter a valid phone number for',
            signupFailed: 'Signup failed',
            signupErrorGeneric: 'An error occurred during signup',
            createAccountBtn: 'Create Account',
            contactNumber: 'Contact Number',
            alreadyHaveAccount: 'Already have an account?',
            signInLink: 'Sign In',
            male: 'Male',
            female: 'Female',
            otherGender: 'Other',
            dashboardCaretakerPrefix: 'Caretaker:',
            dashboardGuestUser: 'User',
            medicineCardReadAloud: 'Read aloud',
            historyAllTime: 'All time log',
            historyStatusTaken: 'Taken',
            historyStatusMissed: 'Missed',
            addMedNameLabel: 'Medicine name',
            addMedDosageLabel: 'Dosage',
            addMedFrequencyLabel: 'Frequency',
            addMedScheduleLabel: 'Schedule time',
            addMedSave: 'Save medicine',
            addMedPlaceholderName: 'e.g. Aspirin',
            addMedPlaceholderDosage: 'e.g. 1 Tablet / 500mg',
            freqDaily: 'Daily',
            freqTwice: 'Twice Daily',
            freqWeekly: 'Weekly',
            freqAsNeeded: 'As needed',
            addMedFailed: 'Failed to add medicine',
            ctAllPatients: 'All Patients',
            ctAddPatient: 'Add Patient',
            ctMonitoringAll: 'Monitoring: All Patients',
            ctMonitoringPrefix: 'Monitoring:',
            ctActiveSession: 'Active Monitoring Session',
            ctAdherence: 'Adherence',
            ctNextDose: 'Next Dose',
            ctMissed: 'Missed',
            ctPatientSchedule: "Patient's Schedule",
            ctFetchingData: 'Fetching patient data…',
            ctNoMedicineRecords: 'No medicine records found for this patient.',
            ctEmailPlaceholder: 'patient@example.com',
            profileLanguage: 'Language',
            profileNotifications: 'Notifications',
            profilePrivacySecurity: 'Privacy & Security',
            privacyModalTitle: 'Privacy & Security',
            privacyModalBody:
                'Your data is encrypted and stored securely. We only use your information to provide personalized medicine reminders.',
            privacyAccountSecure: 'Account Secure',
            closeBtn: 'Close',
            englishLabel: 'English',
            urduLabel: 'Urdu',
            verifyEmailMissing: 'Email is missing. Please try signing up or logging in again.',
            verifySuccessMsg: 'Verification successful!',
            verifyFailed: 'Verification failed',
            verifyErrorGeneric: 'An error occurred during verification',
            resendSuccess: 'New code sent to your email!',
            resendFailed: 'Failed to resend code',
            resendError: 'Error resending code',
            forgotPasswordTitle: 'Forgot Password',
            forgotPasswordSubtitle: "Enter your email address and we'll send you a code to reset your password.",
            emailAddressLabel: 'Email address',
            sendResetCode: 'Send reset code',
            backToLogin: 'Back to login',
            resetPasswordTitle: 'Reset Password',
            resetStep1Subtitle: 'Enter the code sent to your email.',
            resetStep2Subtitle: 'Choose a new password.',
            verificationCodeLabel: 'Verification code',
            verifyCodeBtn: 'Verify code',
            confirmNewPass: 'Confirm new password',
            passwordsMismatch: 'Passwords do not match',
            passwordMin6: 'Password must be at least 6 characters long',
            resetSuccess: 'Password reset successful!',
            aiAnalyzing: 'Analyzing your medicines with AI…',
            aiAddMedicinesHint: 'Add medicines to get personalized AI suggestions!',
            aiAskTitle: 'Ask Med-Mate AI',
            aiAskSubtitle:
                'Have questions about side effects or how to take your medications? Tap to start a private chat.',
            aiStartChat: 'Start Chat',
            aiAssistantTitle: 'Med-Mate Assistant',
            aiOnlineStatus: 'Online',
            aiChatPlaceholder: 'Ask me anything…',
            aiDisclaimer: 'Medical advice is for information only. Consult a doctor for emergencies.',
            aiChatWelcome:
                "Hello! I'm your Med-Mate AI. How can I help you with your medications today?",
            aiChatError: "Sorry, I'm having trouble connecting right now. Please try again.",
            countrySearchPlaceholder: 'Search country…',
            countryNoResults: 'No results',
            adminAssignmentFailed: 'Assignment failed',
            emailPlaceholderGeneric: 'john@example.com',
            phonePlaceholderPk: '3001234567',
            addPatientFailed: 'Could not add patient',
            noEmailProvided: 'No email provided',
            verifyEmailTitle: 'Verify Email',
            verifyCodeSentPrefix: 'Enter the code sent to',
            verifyNeedEmail: 'Please provide your email to continue',
            verifyAndContinue: 'Verify & Continue',
            didntReceiveCode: "Didn't receive the code?",
            resendCodeButton: 'Resend Code',
            resendInPrefix: 'Resend in',
            backToSignup: 'Back to Signup',
            resetCodeSentTo: 'Enter the 6-digit code sent to',
            resetNewPasswordHint: 'Create a strong new password for your account.',
            resetCodeLabel: 'Reset code',
            resetPasswordBtn: 'Reset password',
            invalidResetCode: 'Invalid or expired code',
        },
        ur: {
            appName: 'میڈ میٹ',
            dashboard: 'ڈیش بورڈ',
            myMeds: 'میری ادویات',
            history: 'تاریخچه',
            suggestions: 'تجاویز',
            profile: 'پروفائل',
            addMedicine: 'دوا شامل کریں',
            nextDose: 'اگلی خوراک',
            missed: 'چھوٹی ہوئی',
            taken: 'لی گئی',
            logout: 'لاگ آؤٹ',
            welcome: 'خوش آمدید',
            upcoming: 'آنے والی',
            completedMissed: 'مکمل اور چھوٹ جانے والی',
            noUpcoming: 'آج کے لئے کوئی دوا نہیں!',
            takeAction: 'کھائیں',
            adminPanel: 'ایڈمن پینل',
            adminSubtitle: 'سسٹم کا جائزہ اور مریض تفویض',
            loadingStats: 'اعداد و شمار لوڈ ہو رہے ہیں…',
            systemOverview: 'سسٹم کا جائزہ',
            patients: 'مریض',
            caretakers: 'دیکھ بھال کرنے والے',
            unassignedPatients: 'غیر تفویض شدہ مریض',
            totalMedicines: 'کل ادویات',
            admins: 'ایڈمن',
            verifiedUsers: 'تصدیق شدہ صارفین',
            totalUsers: 'کل صارفین',
            caretakersPatientsTitle: 'دیکھ بھال کرنے والے اور مریض',
            name: 'نام',
            email: 'ای میل',
            password: 'پاس ورڈ',
            assignedPatients: 'تفویض شدہ مریض',
            noCaretakers: 'ابھی کوئی دیکھ بھال کرنے والا رجسٹر نہیں۔',
            unassignedSection: 'غیر تفویض شدہ مریض',
            allPatientsAssigned: 'ہر مریض کا دیکھ بھال کرنے والا ہے۔',
            selectCaretaker: 'دیکھ بھال کرنے والا منتخب کریں',
            assign: 'تفویض کریں',
            assigning: 'تفویض ہو رہی ہے…',
            rolePatient: 'مریض',
            roleCaretaker: 'دیکھ بھال کرنے والا',
            roleAdmin: 'منتظم',
            patientsMedicinesTitle: 'مریض اور ادویات',
            patientsMedicinesSubtitle: 'کون سا مریض کون سی ادویات استعمال کر رہا ہے',
            caretakerLabel: 'دیکھ بھال کرنے والا',
            unassignedCaretaker: 'غیر تفویض',
            medName: 'دوا',
            medDosage: 'خوراک',
            medTime: 'وقت',
            medStatus: 'حالت',
            medType: 'قسم',
            noMedicinesListed: 'ابھی کوئی دوا شامل نہیں۔',
            noPatientsYet: 'کوئی مریض رجسٹر نہیں۔',
            editName: 'نام تبدیل کریں',
            changePassword: 'پاس ورڈ تبدیل کریں',
            firstNameLabel: 'پہلا نام',
            lastNameLabel: 'آخری نام',
            saveChanges: 'محفوظ کریں',
            cancel: 'منسوخ',
            currentPasswordLabel: 'موجودہ پاس ورڈ',
            newPasswordLabel: 'نیا پاس ورڈ',
            confirmPasswordLabel: 'نئے پاس ورڈ کی تصدیق',
            updatePasswordBtn: 'پاس ورڈ اپ ڈیٹ کریں',
            passwordsDoNotMatch: 'نئے پاس ورڈ مماثل نہیں',
            nameUpdateSuccess: 'نام اپ ڈیٹ ہو گیا',
            passwordUpdateSuccess: 'پاس ورڈ اپ ڈیٹ ہو گیا',
            saving: 'محفوظ ہو رہا ہے…',
            updatingPassword: 'اپ ڈیٹ ہو رہا ہے…',
            languageUpdated: 'زبان تبدیل ہو گئی!',
            successTitle: 'مکمل',
            gotIt: 'ٹھیک ہے',
            medicineForPatient: 'دوا کس مریض کے لیے',
            selectPatientForMedicine: 'براہ کرم مریض منتخب کریں',
            noPatientsAddFirst: 'کوئی مریض نہیں — پہلے مریض شامل کریں',
            selectPatientPlaceholder: 'مریض منتخب کریں',
            addNewPatientTitle: 'نیا مریض شامل کریں',
            addNewPatientSubtitle: 'سائن اپ جیسے ہی تفصیلات درج کریں۔ اکاؤنٹ خود بخود تصدیق شدہ ہو گا۔',
            dateOfBirthLabel: 'تاریخ پیدائش',
            genderLabel: 'جنس',
            phoneLabel: 'رابطہ نمبر',
            patientPasswordHint: 'مریض اس پاس ورڈ سے لاگ ان کر سکتا ہے۔',
            addPatientBtn: 'مریض شامل کریں',
            addPatientNameError: 'پہلا اور آخری نام کم از کم 3 حروف',
            passwordMin8: 'پاس ورڈ کم از کم 8 حروف',
            selectGender: 'جنس منتخب کریں',
            invalidPhone: 'درست فون نمبر درج کریں',
            callPatient: 'کال کریں',
            selectPatientToCall: 'کال کے لیے اوپر سے مریض منتخب کریں',
            selectPatientToCallShort: 'کال کے لیے مریض منتخب کریں',
            caretakerDashboard: 'دیکھ بھال ڈیش بورڈ',
            addPatientNav: 'مریض شامل کریں',
            switchToUrdu: 'اردو میں',
            switchToEnglish: 'انگریزی',
            voiceCommandTitle: 'آواز کا حکم',
            voiceListening: 'سن رہا ہوں…',
            voiceCommandBtn: 'آواز کا حکم',
            voiceHeardPrefix: 'سنا:',
            voiceInvalidCommand: 'غلط حکم',
            loginWelcomeBack: 'خوش آمدید',
            loginSubtitle: 'اپنے اکاؤنٹ میں سائن ان کریں',
            enterEmailPlaceholder: 'اپنا ای میل درج کریں',
            forgotPasswordLink: 'پاس ورڈ بھول گئے؟',
            signInBtn: 'سائن ان',
            noAccount: 'اکاؤنٹ نہیں ہے؟',
            createAccountLink: 'اکاؤنٹ بنائیں',
            loginFailed: 'لاگ ان ناکام',
            loginErrorGeneric: 'لاگ ان کے دوران خرابی',
            signupTitle: 'اکاؤنٹ بنائیں',
            signupSubtitle: 'آج ہی میڈ میٹ میں شامل ہوں',
            signupFirstNameError: 'پہلا نام کم از کم 3 حروف',
            signupLastNameError: 'آخری نام کم از کم 3 حروف',
            signupPasswordError: 'پاس ورڈ کم از کم 8 حروف',
            signupGenderError: 'جنس منتخب کریں',
            signupPhoneError: 'درست فون نمبر درج کریں',
            signupFailed: 'سائن اپ ناکام',
            signupErrorGeneric: 'سائن اپ کے دوران خرابی',
            createAccountBtn: 'اکاؤنٹ بنائیں',
            contactNumber: 'رابطہ نمبر',
            alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟',
            signInLink: 'سائن ان',
            male: 'مرد',
            female: 'عورت',
            otherGender: 'دیگر',
            dashboardCaretakerPrefix: 'دیکھ بھال:',
            dashboardGuestUser: 'صارف',
            medicineCardReadAloud: 'آواز میں سنیں',
            historyAllTime: 'مکمل لاگ',
            historyStatusTaken: 'لی گئی',
            historyStatusMissed: 'چھوٹ گئی',
            addMedNameLabel: 'دوا کا نام',
            addMedDosageLabel: 'خوراک',
            addMedFrequencyLabel: 'تعدد',
            addMedScheduleLabel: 'وقت',
            addMedSave: 'دوا محفوظ کریں',
            addMedPlaceholderName: 'مثلاً اسپرین',
            addMedPlaceholderDosage: 'مثلاً 1 گولی',
            freqDaily: 'روزانہ',
            freqTwice: 'دن میں دو بار',
            freqWeekly: 'ہفتہ وار',
            freqAsNeeded: 'ضرورت کے مطابق',
            addMedFailed: 'دوا شامل نہ ہو سکی',
            ctAllPatients: 'تمام مریض',
            ctAddPatient: 'مریض شامل کریں',
            ctMonitoringAll: 'نگرانی: تمام مریض',
            ctMonitoringPrefix: 'نگرانی:',
            ctActiveSession: 'فعال نگرانی',
            ctAdherence: 'پابندی',
            ctNextDose: 'اگلی خوراک',
            ctMissed: 'چھوٹی',
            ctPatientSchedule: 'مریض کا شیڈول',
            ctFetchingData: 'ڈیٹا لوڈ ہو رہا ہے…',
            ctNoMedicineRecords: 'اس مریض کی کوئی دوا نہیں ملی۔',
            ctEmailPlaceholder: 'patient@example.com',
            profileLanguage: 'زبان',
            profileNotifications: 'اطلاعات',
            profilePrivacySecurity: 'رازداری اور سیکیورٹی',
            privacyModalTitle: 'رازداری اور سیکیورٹی',
            privacyModalBody:
                'آپ کا ڈیٹا محفوظ طریقے سے رکھا جاتا ہے۔ ہم صرف دوا کی یاد دہانی کے لیے استعمال کرتے ہیں۔',
            privacyAccountSecure: 'اکاؤنٹ محفوظ',
            closeBtn: 'بند کریں',
            englishLabel: 'English',
            urduLabel: 'اردو',
            verifyEmailMissing: 'ای میل نہیں ملی۔ دوبارہ کوشش کریں۔',
            verifySuccessMsg: 'تصدیق ہو گئی!',
            verifyFailed: 'تصدیق ناکام',
            verifyErrorGeneric: 'تصدیق میں خرابی',
            resendSuccess: 'نیا کوڈ ای میل بھیج دیا گیا!',
            resendFailed: 'کوڈ نہ بھیجا جا سکا',
            resendError: 'کوڈ بھیجنے میں خرابی',
            forgotPasswordTitle: 'پاس ورڈ بھول گئے',
            forgotPasswordSubtitle: 'ای میل درج کریں، ہم ری سیٹ کوڈ بھیجیں گے۔',
            emailAddressLabel: 'ای میل',
            sendResetCode: 'کوڈ بھیجیں',
            backToLogin: 'لاگ ان پر واپس',
            resetPasswordTitle: 'پاس ورڈ ری سیٹ',
            resetStep1Subtitle: 'ای میل پر بھیجا کوڈ درج کریں۔',
            resetStep2Subtitle: 'نیا پاس ورڈ منتخب کریں۔',
            verificationCodeLabel: 'تصدیقی کوڈ',
            verifyCodeBtn: 'کوڈ تصدیق کریں',
            confirmNewPass: 'نئے پاس ورڈ کی تصدیق',
            passwordsMismatch: 'پاس ورڈ مماثل نہیں',
            passwordMin6: 'پاس ورڈ کم از کم 6 حروف',
            resetSuccess: 'پاس ورڈ ری سیٹ ہو گیا!',
            aiAnalyzing: 'AI سے تجزیہ ہو رہا ہے…',
            aiAddMedicinesHint: 'ذاتی تجاویز کے لیے پہلے ادویات شامل کریں!',
            aiAskTitle: 'میڈ میٹ AI سے پوچھیں',
            aiAskSubtitle: 'ضمنی اثرات یا خوراک کے بارے میں؟ ذاتی چیٹ شروع کریں۔',
            aiStartChat: 'چیٹ شروع کریں',
            aiAssistantTitle: 'میڈ میٹ اسسٹنٹ',
            aiOnlineStatus: 'آن لائن',
            aiChatPlaceholder: 'کچھ بھی پوچھیں…',
            aiDisclaimer: 'یہ صرف معلومات ہیں۔ ایمرجنسی میں ڈاکٹر سے رجوع کریں۔',
            aiChatWelcome:
                'سلام! میں میڈ میٹ AI ہوں۔ آج آپ کی ادویات میں کیسے مدد کروں؟',
            aiChatError: 'کنکشن میں مسئلہ ہے۔ دوبارہ کوشش کریں۔',
            countrySearchPlaceholder: 'ملک تلاش…',
            countryNoResults: 'کچھ نہیں ملا',
            adminAssignmentFailed: 'تفویض ناکام',
            emailPlaceholderGeneric: 'john@example.com',
            phonePlaceholderPk: '3001234567',
            addPatientFailed: 'مریض شامل نہ ہو سکا',
            noEmailProvided: 'ای میل نہیں',
            verifyEmailTitle: 'ای میل تصدیق',
            verifyCodeSentPrefix: 'بھیجا گیا کوڈ درج کریں',
            verifyNeedEmail: 'جاری رکھنے کے لیے ای میل درج کریں',
            verifyAndContinue: 'تصدیق کریں اور آگے',
            didntReceiveCode: 'کوڈ نہیں ملا؟',
            resendCodeButton: 'دوبارہ کوڈ',
            resendInPrefix: 'دوبارہ',
            backToSignup: 'سائن اپ پر واپس',
            resetCodeSentTo: '6 ہندسوں کا کوڈ درج کریں، بھیجا گیا:',
            resetNewPasswordHint: 'نیا مضبوط پاس ورڈ بنائیں۔',
            resetCodeLabel: 'ری سیٹ کوڈ',
            resetPasswordBtn: 'پاس ورڈ ری سیٹ',
            invalidResetCode: 'کوڈ غلط یا ختم',
        },
    };

    return (
        <LanguageContext.Provider
            value={{ language, setLanguage, toggleLanguage, t: translations[language] }}
        >
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
